spring.application.name=product-service
spring.datasource.url=jdbc:postgresql://localhost:5432/product-service
spring.datasource.username=postgres
spring.datasource.password=789789
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database=POSTGRESQL

server.port=8081
